name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows

    steps:
    - uses: ./simple-web
    - name: Build the Docker image
      run: docker build . -t simple-web
